version: '3.9'

services:
  model:
    build: 
      context: ../
      dockerfile: './Dockerfile'
      target: dev
    working_dir: ${WORKING_DIR}
    container_name: dtcc-model
    image: dtcc-model-image
    stdin_open: true 
    tty: true 
    volumes:
      - ../:${WORKING_DIR}
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE




  

