version: '3.9'

services:
  model:
    build: 
      context: ../
      dockerfile: './docker/Dockerfile'
      target: dev
    working_dir: /home/dtcc/dtcc-model
    container_name: dtcc-model
    image: dtcc-model-image
    stdin_open: true 
    tty: true 
    volumes:
      - ../:/home/dtcc/dtcc-model
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE




  

