#!/usr/bin/env bash

CPP_DIR=./cpp/protobuf
PYTHON_DIR=./dtcc_model/

echo "Building C++ classes..."
protoc --cpp_out=$CPP_DIR dtcc.proto

echo "Building Python classes..."
protoc --python_out=$PYTHON_DIR dtcc.proto
