name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: pip install 
      run: pip install .
    - name: cmake install 
      run: cd build && cmake .. && make all && sudo make install && cd ..
    - name: run tests
      run: cd tests && sh run-tests.sh
    - name: cleanup op
      run : sudo find /home/ubuntu/Runner/actions-runner/_work/${{ github.event.repository.name }}/. -name . -o -prune -exec rm -rf -- {} + || true
